/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }


    @Test
    public void testRollMethod() {
int number = 4;
int[] result = Library.roll(number);
assertEquals(number,result.length);
    }

    @Test public void testRollBetweenOneAndSix(){
        int[] result = Library.roll(3);
      for(int number : result ){
          boolean actual = number > 0 && number<7;
          assertTrue(actual);
      }

    }
}
