/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n) {
        int[] counts = new int[n];
        for (int i = 0; i < counts.length; i++) {
            counts[i] = (int) (Math.random() * 6);
        }
        for (int num = 0; num < counts.length; num++) {

            System.out.println(num + "\t" + counts[num]);
        }//end for
        return counts;
    }


}




